CREATE TABLE `customer` (
id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
name VARCHAR(64) NOT NULL COMMENT 'ユーザ名',
gid VARCHAR(64) NOT NULL COMMENT 'Google ユーザID',
gname VARCHAR(64) NOT NULL COMMENT 'Google ユーザ名',
gmail VARCHAR(64) NOT NULL COMMENT 'Google Gmail',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
version INT UNSIGNED DEFAULT 0,

PRIMARY KEY(id),
UNIQUE KEY(name),
INDEX `idx_name` (`name`)
) COMMENT '利用者テーブル'
;
