@startuml

actor frontend as fe
box backend #ddeeff
participant api
database inmemory_db as db
participant cron_job as cron
end box
database s3 as s3

== delete shiori ==

fe -> api: DELETE /v1/shiori/${shiori_id}

opt invalid param
  api -> fe: error response
end opt

opt invalid user
  api -> fe: error response
end opt

api -> db: delete a shiori in db
note right: logical delete
db -> api:

opt not found
  api -> fe: error response
end opt

opt general db error
  api -> fe: error response
end opt

api -> fe: success response

@enduml
