@startuml

actor frontend as fe
box backend #ddeeff
participant api
database inmemory_db as db
participant cron_job as cron
end box
database s3 as s3

== get page ==

fe -> api: GET /v1/page/${page_id}

opt invalid param
  api -> fe: error response
end opt

opt invalid user
  api -> fe: error response
end opt

api -> db: query db to get page
note right: ignore if logical deleted
db -> api:

opt not found
  api -> fe: error response
end opt

opt general db error
  api -> fe: error response
end opt

api -> db: query db to get block with page.id
note right: ignore if logical deleted
db -> api:

api -> api: construct page list with block list

api -> fe: page list

@enduml
