spring:
  application:
    name: tiori
  h2:
    console:
      enabled: true  # access from http://localhost:8080/h2-console/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tiori;MODE=MySQL  # create h2's database automatically if not exist
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pw}
    initialize: true
  sql:
    init:
      schema-locations: classpath:schema.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:421957709511-ef6if70v7q721b1p3vscn7or9si7uoat.apps.googleusercontent.com}
            client-secret: {GOOGLE_CLIENT_SECRET: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}
            # special callback url, which automatically stores user auth info
            redirect-uri: ${GOOGLE_REDIRECT_ID:http://localhost:8080/login/oauth2/code/google}
server:
  error:
    include-stacktrace: never

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}
