-- database is automatically created with spring.datasource.url in application.yml
-- https://h2database.com/html/features.html#database_url
-- CREATE DATABASE IF NOT EXISTS tiori CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `customer` (
id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
uid VARCHAR(32) NOT NULL COMMENT 'ユーザID',
name VARCHAR(32) NOT NULL COMMENT 'ユーザ名',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
version INT UNSIGNED DEFAULT 0,
is_deleted BOOLEAN DEFAULT FALSE,
PRIMARY KEY(id),
UNIQUE KEY(uid),
INDEX `idx_uid` (`uid`),
INDEX `idx_name` (`name`)
) COMMENT '利用者テーブル'
;

CREATE TABLE `shiori` (
id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
customer_id BIGINT NOT NULL COMMENT 'customer.id',
title VARCHAR(32) NOT NULL COMMENT 'タイトル',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
version INT UNSIGNED DEFAULT 0,
is_deleted BOOLEAN DEFAULT FALSE,
PRIMARY KEY(id)
) COMMENT 'しおりテーブル'
;

CREATE TABLE `page` (
id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
shiori_id BIGINT NOT NULL COMMENT 'shiori.id',
layout_json JSON NOT NULL COMMENT 'レイアウト',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
version INT UNSIGNED DEFAULT 0,
is_deleted BOOLEAN DEFAULT FALSE,
PRIMARY KEY(id)
) COMMENT 'ページテーブル'
;

CREATE TABLE `block` (
id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
page_id BIGINT NOT NULL COMMENT 'page.id',
type VARCHAR(32) NOT NULL COMMENT '種別',
content_json JSON NOT NULL COMMENT 'コンテンツ',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
version INT UNSIGNED DEFAULT 0,
is_deleted BOOLEAN DEFAULT FALSE,
PRIMARY KEY(id)
) COMMENT 'ブロックテーブル'
;
